# generated by maixhub, tested on maixpy v0.6.0_2_g9720594
# copy files to TF card and plug into board and power on

import sensor, image, lcd, time, machine
from maix import KPU, utils
import gc, sys

# SEE <https://wiki.sipeed.com/soft/maixpy/zh/course/ai/image/1000_type_classifier.html>
# 不要烧录到 main.py 里，不然以下两行会触发无休止的重置
#utils.gc_heap_size(200*1024)
#machine.reset()

input_size = (224, 224)
labels = ['car', 'bicycle', 'pedestrian', 'greening']
kpu = KPU()

def lcd_show_except(e):
    import uio
    err_str = uio.StringIO()
    sys.print_exception(e, err_str)
    err_str = err_str.getvalue()
    img = image.Image(size=input_size)
    img.draw_string(0, 10, err_str, scale=1, color=(0xff,0x00,0x00))
    lcd.display(img)

def main(labels, model_addr, sensor_window=input_size, lcd_rotation=0, sensor_hmirror=False, sensor_vflip=False):
    gc.collect()
    sensor.reset()
    sensor.set_pixformat(sensor.RGB565)
    sensor.set_framesize(sensor.QVGA)
    sensor.set_windowing(sensor_window)
    sensor.set_hmirror(sensor_hmirror)
    sensor.set_vflip(sensor_vflip)
    sensor.run(1)

    lcd.init(type=1)
    lcd.rotation(lcd_rotation)
    lcd.clear(lcd.WHITE)
    '''
    if not labels:
        with open('labels.txt','r') as f:
            exec(f.read())
    if not labels:
        print("no labels.txt")
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "no labels.txt", color=(255, 0, 0), scale=2)
        lcd.display(img)
        return 1
    '''
    try:
        img = image.Image("startup.jpg")
        img.draw_string(90, 110, "loading model...", color=(80, 255, 255), scale=2)
        lcd.display(img)
    except Exception:
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "loading model...", color=(255, 255, 255), scale=2)
        lcd.display(img)
    try:
        print('init done!')
        task = None
        task = kpu.load_kmodel(model_addr) # OSError SEE
        # <https://github.com/sipeed/MaixPy/blob/8fcd84a58a35f348558d4c095ae9cce646f9d303/components/micropython/port/src/Maix/Maix_kpu.c>
        # It might be trigered by low RAM size
        print('load done!')
        while(True):
            img = sensor.snapshot()
            #img_2 = img.resize((..input_size, 3))
            #continue
            t = time.ticks_ms()
            #fmap = kpu.forward(task, img)
            plist = kpu.run_with_output(img, getlist=True)
            t = time.ticks_ms() - t
            #plist=fmap[:]
            pmax=max(plist)
            max_index=plist.index(pmax)
            img.draw_string(0,0, "%.2f : %s" %(pmax, labels[max_index].strip()), scale=2, color=(255, 0, 0))
            print("%.2f : %s" %(pmax, labels[max_index].strip()))
            img.draw_string(0, 200, "t:%dms" %(t), scale=2, color=(255, 0, 0))
            lcd.display(img)
            del img
    except Exception as e:
        raise e
    finally:
        if not task is None:
            kpu.deinit(task)


if __name__ == "__main__":
    try:
        kpu.deinit()
        main(labels=labels, model_addr="/sd/KPU/model-50627.kmodel")
    except Exception as e:
        sys.print_exception(e)
        lcd_show_except(e)
    finally:
        gc.collect()
